[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc_core = { workspace = true }
anyhow = { workspace = true }
colored = "3.0.0"
itertools = "0.14.0"
pastey = "0.1.1"
rayon = "1.11.0"
regex = "1.12.2"
rustc-hash = "2.1.1"
