[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_core = { workspace = true }
anyhow = { workspace = true }
colored = "2.1.0"
itertools = "0.13.0"
paste = "1.0.15"
rayon = "1.10.0"
regex = "1.11.1"
