[package]
name = "aoc_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = "0.4.42"
clap = { version = "4.5.50", features = ["derive"] }
ureq = "3.1.2"
webbrowser = "1.0.6"
