[package]
name = "aoc_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
ureq = "2.11.0"
webbrowser = "1.0.3"
